# 闭包

在了解闭包之前，我们需要知道什么是作用域链

## 作用域链

当我们访问一个变量的时候，JavaScript 引擎首先会在**当前作用域**寻找这个变量。如果当前作用域没有这个变量，就会去**上一层作用域**寻找，如果还是没有，就继续往上，直到**全局作用域**都找不到时，返回`undefined`

就拿下面的代码：

```js
var windowVar = "windowVar"
function fn() {
	var fnVar = "fnVar"
	function inner() {
		var innerVar = "inner"
		console.log(innerVar)
		console.log(fnVar)
		console.log(windowVar)
		console.log(a)
	}
}
```

打印四个变量，`innerVar`、`fnVar`、`windowVar`、`a`

- 第一个`innerVar`，他首先会在当前作用域即`inner`函数内寻找，找到返回
- 第二个`fnVar`，先当前作用域寻找，没有找到，去上一层作用域即`fn`函数内寻找，找到了，返回
- 第三个`windowVar`，先当前作用域寻找，没有找到，去上一层`fn`里面找，没有找到，再去上一层，到达全局作用域，找到了，返回
- 第四个`a`，先当前作用域找，没有去上一层`fn`里面找，没有去全局作用域找，都没有，返回`undefined`

## 闭包

理解了什么是作用域链，我们就可以学习什么是闭包了。

闭包指的是即使外部函数**已经不存在**，也可以获取作用域链上变量的函数。

这个我们通过代码例子来理解一下：

```js
function outer() {
	const a = 1
	function f() {
		console.log(a)
	}
	return f
}
let fn = outer()
fn()
```

现在有一个外部函数`outer`，定义了一个变量`a`，然后里面有一个内部函数`f`，在内部函数里面访问外部函数的变量`a`，这个打印的结果是`1`。

通过上面的作用域链，我们知道`f`打印`a`，先当前作用域寻找，没有就去上一层即`outer`里面寻找，因此打印结果是`1`。

那么什么是闭包呢？这个`a`变量和函数`f`把它理解成整体，他们就形成了闭包。

为什么这么说呢，我们看下面`let fn = outer()`，在`outer`执行结束之后，理论上`outer`内部定义的所有变量都会被销毁，比如下面的：

```js
function outer() {
	const a = 1
	const b = 123
	function f() {
		console.log(a)
	}
	return f
}
```

`b`变量在`outer`执行结束之后就会被销毁，但是`a`是特殊的，它不会被销毁，因为`f`函数在内部用到了它，它们之间形成了闭包，所以`a`不会被销毁。

说简单点就是，`a`变量今后会被用到，所以 JS 引擎在垃圾回收时不会销毁它。

它们是否符合闭包定义呢？符合，外部函数`outer`在执行结束后就销毁了，而我们在执行`fn`的时候仍然可以访问作用域链上的变量即`a`变量，所以符合闭包定义。

我们还可以通过控制台，找到源代码，在打印那行打个断点，然后查看右下角：

![image-20240822143655014](https://chen-1320883525.cos.ap-chengdu.myqcloud.com/img/image-20240822143655014.png)

如果是英文，就是`Closure`，单词就是闭包。

## 问题

一定要在外部函数中 return 内部函数，才会形成闭包吗？

就拿上面的例子，我不 return 内部函数，而是调用：

```js
function outer() {
	const a = 1
	const b = 123
	function f() {
		console.log(a)
	}
	f()
}
```

然后我们再查看控制台，会发现还是形成了闭包：

![image-20240822144055420](https://chen-1320883525.cos.ap-chengdu.myqcloud.com/img/image-20240822144055420.png)

所以即使没有 return，只要我们符合闭包的定义，依旧会形成闭包

## 缺点

闭包的缺点：**可能**会造成内存泄漏，注意是可能。

我们需要根据场景来判断是否会内存泄漏：

```js
function fn() {
	var element = document.getElementById("button")
	// 模拟一个超级大的资源
	var someResource = new Array(1000).join("*")

	element.addEventListener("click", () => {
		console.log(someResource)
	})
}
fn()
```

这个场景就是，给按钮添加一个点击事件，点击后获取一个超大的资源，看起来好像没有什么问题。我们来分析一下，我们在外部函数定义超大资源，然后内部函数访问它打印，按照闭包定义，这里形成了闭包。

我们运行一下，查看是否形成：

![image-20240822144813450](https://chen-1320883525.cos.ap-chengdu.myqcloud.com/img/image-20240822144813450.png)

可以看到，闭包形成了，这就造成一个问题，如果有一天，这个`button`都不存在了，也就是我们用不到它了，但是这个超大资源数组还会存在，因为它形成了闭包，不会被垃圾回收，这就会造成内存泄漏。

解决方法也很简单，就是在不用它之后，**移除**监听事件。
